dhtmdwo/Matfia-Eatzzy-Back

matfiaBack/app-api/src/main/java/com/example/appapi/like/LikeController.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/LikeRepository.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/LikeService.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/model/Like.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/model/LikeDto.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/PaymentController.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/PaymentRepository.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/PaymentService.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/model/Payment.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/model/PaymentDto.java
>>
>> 좋아요 엔티티 구현 완료
>>
>> Resolves : #23
close #23
=> [feat] 좋아요 엔티티 구현 (#23)

matfiaBack/app-api/src/main/java/com/example/appapi/like/LikeController.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/LikeRepository.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/LikeService.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/LikesController.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/LikesRepository.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/LikesService.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/model/LikeDto.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/model/Likes.java, matfiaBack/app-api/src/main/java/com/example/appapi/like/model/LikesDto.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/model/Payment.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/model/PaymentDto.java
결제 앤티티 생성
Resolves : #14
close #14
=> [feat] 결제 엔티티 생성(#14)

matfiaBack/app-api/build.gradle, matfiaBack/app-api/src/main/java/com/example/appapi/likes/LikesController.java, matfiaBack/app-api/src/main/java/com/example/appapi/likes/LikesRepository.java, matfiaBack/app-api/src/main/java/com/example/appapi/likes/LikesService.java, matfiaBack/app-api/src/main/java/com/example/appapi/likes/model/Likes.java, matfiaBack/app-api/src/main/java/com/example/appapi/likes/model/LikesDto.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/PaymentController.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/PaymentRepository.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/PaymentService.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/model/PaymentDto.java
결제 목록 조회
Resolves : #15
close #15
=> [feat] 결제 목록 조회(#15)

matfiaBack/app-api/src/main/java/com/example/appapi/payment/PaymentController.java, matfiaBack/app-api/src/main/java/com/example/appapi/payment/PaymentService.java
결제 상세 조회
Resolves : #16
close #16
=> [feat] 결제 상세 조회(#16)

matfiaBack/app-api/src/main/java/com/example/appapi/likes/LikesController.java, matfiaBack/app-api/src/main/java/com/example/appapi/likes/LikesService.java
좋아요 상세 조회
Resolves : #25
close #25
=> [feat] 좋아요 상세  조회(#25)

.idea/gradle.xml, .idea/workspace.xml, matfiaBack/app-api/src/main/java/com/example/appapi/orders/Orders.java, matfiaBack/app-api/src/main/java/com/example/appapi/orders/OrdersController.java, matfiaBack/app-api/src/main/java/com/example/appapi/orders/OrdersDto.java, matfiaBack/app-api/src/main/java/com/example/appapi/orders/OrdersRepository.java, matfiaBack/app-api/src/main/java/com/example/appapi/orders/OrdersService.java
주문 엔티티 생성
Resolves: #11 
close: #11
=> [feat] 주문 엔티티 생성(#11)

matfiaBack/app-api/src/main/java/com/example/appapi/users/model/Users.java
=> [Feature] User Entity 생성 #2

matfiaBack/app-api/src/main/java/com/example/appapi/product/model/Products.java
=> [feat] 상품(밀키트) 엔티티 생성 (#8)

matfiaBack/app-api/src/main/java/com/example/appapi/orders/OrdersController.java, matfiaBack/app-api/src/main/java/com/example/appapi/orders/OrdersDto.java, matfiaBack/app-api/src/main/java/com/example/appapi/orders/OrdersRepository.java, matfiaBack/app-api/src/main/java/com/example/appapi/orders/OrdersService.java, matfiaBack/app-api/src/main/java/com/example/appapi/orders/model/Orders.java, matfiaBack/app-api/src/main/java/com/example/appapi/orders/model/OrdersDto.java
=> [feat] 주문 등록 기능(#39)

.idea/gradle.xml, .idea/workspace.xml, matfiaBack/app-api/src/main/java/com/example/appapi/likes/LikesController.java, matfiaBack/app-api/src/main/java/com/example/appapi/likes/LikesService.java, matfiaBack/app-api/src/main/java/com/example/appapi/likes/model/LikesDto.java, matfiaBack/app-api/src/main/java/com/example/appapi/paymentmethod/PaymentMethodController.java, matfiaBack/app-api/src/main/java/com/example/appapi/paymentmethod/PaymentMethodRepository.java, matfiaBack/app-api/src/main/java/com/example/appapi/paymentmethod/PaymentMethodService.java, matfiaBack/app-api/src/main/java/com/example/appapi/paymentmethod/model/PaymentMethod.java, matfiaBack/app-api/src/main/java/com/example/appapi/paymentmethod/model/PaymentMethodDto.java
결제 방법 엔티티 생성
Resolves : #34
close #34
=> [Feat] 결제 방법 엔티티 생성 (#34)

matfiaBack/app-api/build.gradle, matfiaBack/app-api/src/main/java/com/example/appapi/store/StoreClosedDayRepository.java, matfiaBack/app-api/src/main/java/com/example/appapi/store/StoreController.java, matfiaBack/app-api/src/main/java/com/example/appapi/store/StoreRepository.java, matfiaBack/app-api/src/main/java/com/example/appapi/store/StoreService.java, matfiaBack/app-api/src/main/java/com/example/appapi/store/model/AllowedStatus.java, matfiaBack/app-api/src/main/java/com/example/appapi/store/model/Store.java, matfiaBack/app-api/src/main/java/com/example/appapi/store/model/StoreClosedDay.java, matfiaBack/app-api/src/main/java/com/example/appapi/store/model/StoreDto.java
식당 엔티티, 식당 휴무일 엔티티 생성
식당 등록 기능 구현
close #5
close #26
=> [Feat] 식당 엔티티 생성, 식당 등록 기능 구현

app-api/src/main/java/com/example/appapi/reviews/ReviewsController.java, app-api/src/main/java/com/example/appapi/reviews/ReviewsRepository.java, app-api/src/main/java/com/example/appapi/reviews/ReviewsService.java, app-api/src/main/java/com/example/appapi/reviews/model/Reviews.java, app-api/src/main/java/com/example/appapi/reviews/model/ReviewsDto.java
리뷰 엔티티 생성, 리뷰 작성 기능 구현
close  #37 
close #17
=> [Feat] 리뷰 엔티티 생성, 리뷰 작성 기능 구현

app-api/src/main/java/com/example/appapi/paymentmethod/PaymentMethodRepository.java
=> [Fix] 결제 방법 목록 조회 (#34)

app-api/src/main/java/com/example/appapi/orders/OrdersController.java, app-api/src/main/java/com/example/appapi/orders/OrdersService.java, app-api/src/main/java/com/example/appapi/orders/model/OrdersDto.java
주문 목록 조회
Resolves: #12
close: #12
=> [feat] 주문 목록 조회 (#12)

app-api/src/main/java/com/example/appapi/reviews/ReviewsController.java, app-api/src/main/java/com/example/appapi/reviews/ReviewsService.java, app-api/src/main/java/com/example/appapi/reviews/model/ReviewsDto.java
=> [Feat] 리뷰 목록 조회 기능 구현

app-api/src/main/java/com/example/appapi/orders/OrdersController.java, app-api/src/main/java/com/example/appapi/orders/OrdersRepository.java, app-api/src/main/java/com/example/appapi/orders/OrdersService.java, app-api/src/main/java/com/example/appapi/orders/model/OrdersDto.java
주문 상세 조회
Resolves: #13
Close #13
=> [feat] 주문 상세 조회 (#13)

app-api/src/main/java/com/example/appapi/users/UsersController.java, app-api/src/main/resources/application.yml, gateway/src/main/resources/application.yml
=> [Fix] yml파일 설정 수정

app-api/src/main/java/com/example/appapi/orders/OrdersController.java
=> [fix] OrdersController URL 경로 수정

app-api/src/main/java/com/example/appapi/product/model/Products.java, matfiaBack/app-api/src/main/java/com/example/appapi/product/images/model/ProductsImages.java, matfiaBack/app-api/src/main/java/com/example/appapi/product/review/images/model/ProductReviewImages.java, matfiaBack/app-api/src/main/java/com/example/appapi/product/review/model/ProductReviews.java
상품과 관련된 엔티티 코드 작성 및 연관관계 설정
closes #63
=> [feat] 상품 연관 관계 설정

common/src/main/java/com/example/BaseException.java, common/src/main/java/com/example/common/BaseResponse.java, common/src/main/java/com/example/common/BaseResponseStatus.java
=> [Feat] BaseResponse, 에러 처리 구현

app-api/src/main/java/com/example/appapi/orders/model/Orders.java
=> [feat] Orders 연관 관계 설정

app-api/src/main/java/com/example/appapi/delivery/DeliveryController.java, app-api/src/main/java/com/example/appapi/delivery/DeliveryRepository.java, app-api/src/main/java/com/example/appapi/delivery/DeliveryService.java, app-api/src/main/java/com/example/appapi/delivery/model/Delivery.java, app-api/src/main/java/com/example/appapi/delivery/model/DeliveryDto.java, app-api/src/main/java/com/example/appapi/orders/model/Orders.java
배송 엔티티 생성 및 주문 테이블과 일대일 연관관계 설정
Resolves: #69
Close: #69
=> [feat] 배송 엔티티 생성 (#69)

app-api/build.gradle, common/src/main/java/com/example/common/BaseResponseStatus.java, common/src/main/resources/application.yml, resv-api/build.gradle
common 모듈 설정 수정, 예외처리 status 수정
=> common 모듈 설정 수정, 예외처리 status 수정

app-api/src/main/java/com/example/appapi/store/StoreController.java, app-api/src/main/java/com/example/appapi/store/StoreService.java, app-api/src/main/java/com/example/appapi/store/model/StoreDto.java
식당 생성 기능 return 타입 BaseResponse로 응답하게 변경
=> [Fix] 식당 생성 기능 return 타입 변경

app-api/src/main/java/com/example/appapi/delivery/DeliveryController.java, app-api/src/main/java/com/example/appapi/delivery/DeliveryRepository.java, app-api/src/main/java/com/example/appapi/delivery/DeliveryService.java, app-api/src/main/java/com/example/appapi/delivery/model/Delivery.java, app-api/src/main/java/com/example/appapi/delivery/model/DeliveryDto.java
배송 등록 기능
Resolves: #72
Close: #72
=> [feat] 배송 등록 기능 (#72)

app-api/src/main/java/com/example/appapi/delivery/DeliveryController.java, app-api/src/main/java/com/example/appapi/delivery/DeliveryService.java, app-api/src/main/java/com/example/appapi/delivery/model/DeliveryDto.java
배송 목록 조회
Resolves: #71
Close: #71
=> [feat] 배송 목록 조회 (#71)

app-api/src/main/java/com/example/appapi/delivery/DeliveryController.java, app-api/src/main/java/com/example/appapi/delivery/DeliveryRepository.java, app-api/src/main/java/com/example/appapi/delivery/DeliveryService.java, app-api/src/main/java/com/example/appapi/delivery/model/DeliveryDto.java
배송 상세내역 조회
Resolves: #70
Close: #70
=> [feat] 배송 상세내역 조회 (#70)

app-api/src/main/java/com/example/appapi/config/SecurityConfig.java, app-api/src/main/java/com/example/appapi/orders/model/Orders.java, app-api/src/main/java/com/example/appapi/payment/model/Payment.java, app-api/src/main/java/com/example/appapi/paymentmethod/model/PaymentMethod.java
Payment 테이블 연관 관계 매핑
Resolves : #85
=> [Fix] Payment 테이블 연관 관계 매핑 (#85)

app-api/src/main/java/com/example/appapi/orders/model/OrderProducts.java
=> [feat] 상품 주문 엔티티 생성 (#82)

app-api/src/main/java/com/example/appapi/product/controller/ProductsController.java, app-api/src/main/java/com/example/appapi/product/images/model/ProductsImages.java, app-api/src/main/java/com/example/appapi/product/images/repository/ProductsImagesRepository.java, app-api/src/main/java/com/example/appapi/product/images/service/ProductsImagesService.java, app-api/src/main/java/com/example/appapi/product/model/Products.java, app-api/src/main/java/com/example/appapi/product/model/ProductsDto.java, app-api/src/main/java/com/example/appapi/product/repository/ProductsRepository.java, app-api/src/main/java/com/example/appapi/product/review/controller/ProductReviewController.java, app-api/src/main/java/com/example/appapi/product/review/images/model/ProductReviewImages.java, app-api/src/main/java/com/example/appapi/product/review/model/ProductReviews.java, app-api/src/main/java/com/example/appapi/product/review/model/ProductReviewsDto.java, app-api/src/main/java/com/example/appapi/product/review/repository/ProductReviewsRepository.java, app-api/src/main/java/com/example/appapi/product/review/service/ProductReviewsService.java, app-api/src/main/java/com/example/appapi/product/service/ProductsService.java
=> [Feat] 상품 기본 기능 최적화 포함  (#88)

app-api/src/main/java/com/example/appapi/category/CategoryController.java, app-api/src/main/java/com/example/appapi/category/CategoryRepository.java, app-api/src/main/java/com/example/appapi/category/CategoryService.java, app-api/src/main/java/com/example/appapi/category/model/Category.java, app-api/src/main/java/com/example/appapi/category/model/CategoryDto.java, app-api/src/main/java/com/example/appapi/store/StoreController.java, app-api/src/main/java/com/example/appapi/store/StoreRepository.java, app-api/src/main/java/com/example/appapi/store/StoreService.java, app-api/src/main/java/com/example/appapi/store/model/Store.java, app-api/src/main/java/com/example/appapi/store/model/StoreDto.java, app-api/src/main/resources/application.yml
식당 조회 기능 구현, 카테고리 구현
close #6 #7
=> [Feat] 식당 조회 기능 구현, 카테고리 구현

app-api/src/main/java/com/example/appapi/store/model/Store.java
=> [Fix] Store 엔티티 수정

app-api/src/main/java/com/example/appapi/category/CategoryController.java, app-api/src/main/java/com/example/appapi/category/CategoryRepository.java, app-api/src/main/java/com/example/appapi/category/CategoryService.java, app-api/src/main/java/com/example/appapi/category/model/Category.java, app-api/src/main/java/com/example/appapi/category/model/CategoryDto.java
=> [Feat] 카테고리 조회 기능 구현

app-api/src/main/java/com/example/appapi/store/review/StoreReviewController.java, app-api/src/main/java/com/example/appapi/store/review/StoreReviewRepository.java, app-api/src/main/java/com/example/appapi/store/review/StoreReviewService.java, app-api/src/main/java/com/example/appapi/store/review/model/StoreReview.java, app-api/src/main/java/com/example/appapi/store/review/model/StoreReviewDto.java
=> [Feature] StoreReview 엔티티 생성

app-api/src/main/java/com/example/appapi/store/review/StoreReviewController.java, app-api/src/main/java/com/example/appapi/store/review/StoreReviewRepository.java, app-api/src/main/java/com/example/appapi/store/review/StoreReviewService.java, app-api/src/main/java/com/example/appapi/store/review/controller/StoreReviewController.java, app-api/src/main/java/com/example/appapi/store/review/model/StoreReview.java, app-api/src/main/java/com/example/appapi/store/review/model/StoreReviewImage.java, app-api/src/main/java/com/example/appapi/store/review/repository/StoreReviewImageRepository.java, app-api/src/main/java/com/example/appapi/store/review/repository/StoreReviewRepository.java, app-api/src/main/java/com/example/appapi/store/review/service/StoreReviewService.java, app-api/src/main/java/com/example/appapi/store/review/service/StoreReviewimageService.java
StoreReviewImage 엔티티 생성, 연관관계 매핑
=> [Feature] StoreReviewImage 엔티티 생성, 연관관계 매핑

app-api/src/main/java/com/example/appapi/store/review/model/StoreReviewDto.java, app-api/src/main/java/com/example/appapi/store/review/service/StoreReviewImageService.java, app-api/src/main/java/com/example/appapi/store/review/service/StoreReviewService.java, app-api/src/main/java/com/example/appapi/store/review/service/StoreReviewimageService.java
=> [Feature] 식당 리뷰 작성, 조회 기능 구현

app-api/src/main/java/com/example/appapi/users/UsersController.java, app-api/src/main/java/com/example/appapi/users/UsersService.java
=> [Feature] User 상세정보 조회 #4

app-api/src/main/java/com/example/appapi/users/UsersController.java, app-api/src/main/java/com/example/appapi/users/UsersService.java, app-api/src/main/java/com/example/appapi/users/model/UsersDto.java
=> [Feature] User 리스트 조회 #3

app-api/src/main/java/com/example/appapi/delivery/model/Delivery.java, app-api/src/main/java/com/example/appapi/orderProducts/OrderProducts.java, app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsController.java, app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsDto.java, app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsRepository.java, app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsService.java, app-api/src/main/java/com/example/appapi/orders/OrdersController.java, app-api/src/main/java/com/example/appapi/orders/OrdersRepository.java, app-api/src/main/java/com/example/appapi/orders/OrdersService.java, app-api/src/main/java/com/example/appapi/orders/model/Orders.java, app-api/src/main/java/com/example/appapi/orders/model/OrdersDto.java, app-api/src/main/java/com/example/appapi/product/repository/ProductsRepository.java, app-api/src/main/java/com/example/appapi/product/service/ProductsService.java
장바구니 -> 주문서 작성 -> 결제 버튼 클릭 시 주문 기능 수정
Resolves: #39
=> [fix] 주문 등록 기능 수정 (#39)

app-api/src/main/java/com/example/appapi/product/model/ProductsDto.java
idx 및 dto 게터 메서드 변경
close #113
=> 상품 화면 dto 필드 수정 (#113)

app-api/src/main/java/com/example/appapi/mypage/model/MypageStoreDto.java, app-api/src/main/java/com/example/appapi/product/review/images/repository/ProductReviewImagesRepository.java, app-api/src/main/java/com/example/appapi/product/review/images/service/ProductReviewsService.java, app-api/src/main/java/com/example/appapi/store/review/service/StoreReviewImageService.java
=> [feat] 포트원 카카오 연동 #117

app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsController.java, app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsRepository.java, app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsService.java, app-api/src/main/java/com/example/appapi/orderProducts/model/OrderProducts.java, app-api/src/main/java/com/example/appapi/orderProducts/model/OrderProductsDto.java, app-api/src/main/java/com/example/appapi/orders/OrdersService.java, app-api/src/main/java/com/example/appapi/orders/model/Orders.java, app-api/src/main/java/com/example/appapi/orders/model/OrdersDto.java
장바구니에서 주문서 작성 이동 시 장바구니에 있던 상품 DB 등록
=> [fix] 장바구니 -> 주문서 작성

app-api/src/main/java/com/example/appapi/orders/OrdersController.java, app-api/src/main/java/com/example/appapi/orders/OrdersRepository.java, app-api/src/main/java/com/example/appapi/orders/OrdersService.java
=> [Feat] 주문 상세보기

app-api/src/main/java/com/example/appapi/orders/OrdersController.java, app-api/src/main/java/com/example/appapi/orders/OrdersRepository.java, app-api/src/main/java/com/example/appapi/orders/OrdersService.java
=> [Fix] 내 주문 내역보기 수정

app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsController.java, app-api/src/main/java/com/example/appapi/orders/OrdersController.java
=> [Fix] 컨트롤러 주석 추가

app-api/src/main/java/com/example/appapi/admin/AdminController.java, app-api/src/main/java/com/example/appapi/admin/AdminRepository.java, app-api/src/main/java/com/example/appapi/admin/AdminService.java, app-api/src/main/java/com/example/appapi/store/model/Store.java, app-api/src/main/java/com/example/appapi/store/model/StoreDto.java
=> [Feature] 관리자 - 식당 전체 조회, 식당등록 허용여부 수정 기능 추가 #105 #106

app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsController.java, app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsService.java, app-api/src/main/java/com/example/appapi/orderProducts/model/OrderProductsDto.java
=> [Fix] OrderProducts 버그 수정

resv-api/build.gradle, resv-api/src/main/java/com/example/resv/ResvApplication.java, resv-api/src/main/java/com/example/resv/config/SecurityConfig.java, resv-api/src/main/java/com/example/resv/config/filter/JwtFilter.java, resv-api/src/main/java/com/example/resv/config/filter/LoginFilter.java, resv-api/src/main/java/com/example/resv/resv/ResvController.java, resv-api/src/main/java/com/example/resv/resv/ResvRepository.java, resv-api/src/main/java/com/example/resv/resv/ResvService.java, resv-api/src/main/java/com/example/resv/resv/model/Resv.java, resv-api/src/main/java/com/example/resv/resv/model/ResvDto.java
=> [Feat] 식당 예약 생성 기능 구현

app-api/src/main/java/com/example/appapi/store/StoreController.java, app-api/src/main/java/com/example/appapi/store/StoreRepository.java, app-api/src/main/java/com/example/appapi/store/StoreService.java, app-api/src/main/java/com/example/appapi/store/model/StoreDto.java
=> [Feat] Mypage 점주 내 상점 조회 기능

app-api/src/main/java/com/example/appapi/admin/AdminController.java, app-api/src/main/java/com/example/appapi/admin/AdminService.java, app-api/src/main/java/com/example/appapi/category/CategoryRepository.java, app-api/src/main/java/com/example/appapi/category/model/Category.java, app-api/src/main/java/com/example/appapi/category/model/CategoryDto.java, app-api/src/main/java/com/example/appapi/config/SecurityConfig.java, app-api/src/main/java/com/example/appapi/store/StoreRepository.java, app-api/src/main/java/com/example/appapi/store/model/Store.java, app-api/src/main/java/com/example/appapi/store/model/StoreDto.java, common/src/main/java/com/example/common/BaseResponseStatus.java
=> [Feature] 관리자 - 카테고리 추가, 수정, 삭제, 식당에 카테고리 지정 #107 #108

app-api/build.gradle
app-api 모듈 빌드 -> QClass 생성가능
빌드하기 전에 환경 변수 추가해야 함
애플리케이션 실행에 필요한 것과 별개
=> [feat] 쿼리 dsl 추가

app-api/src/main/java/com/example/appapi/menus/MenusController.java, app-api/src/main/java/com/example/appapi/menus/MenusRepository.java, app-api/src/main/java/com/example/appapi/menus/MenusService.java, app-api/src/main/java/com/example/appapi/menus/model/Menus.java, app-api/src/main/java/com/example/appapi/menus/model/MenusDto.java
=> [Feat] Menu 추가 기능 구현

app-api/src/main/java/com/example/appapi/menus/MenusController.java, app-api/src/main/java/com/example/appapi/menus/MenusRepository.java, app-api/src/main/java/com/example/appapi/menus/MenusService.java, app-api/src/main/java/com/example/appapi/menus/model/MenusDto.java
=> [Feat] 내 해당 상점 Menu 리스트 보기 기능 추가

app-api/src/main/java/com/example/appapi/menus/MenusController.java, app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsController.java, app-api/src/main/java/com/example/appapi/orders/OrdersController.java, app-api/src/main/java/com/example/appapi/store/StoreController.java
=> [Feat] 주문 기능 스웨거 작성

app-api/src/main/java/com/example/appapi/store/review/controller/StoreReviewController.java
=> [Feat] 가게 리뷰 스웨거 작성

app-api/src/main/java/com/example/appapi/payment/PaymentController.java, app-api/src/main/java/com/example/appapi/product/controller/ProductsController.java, app-api/src/main/java/com/example/appapi/product/review/controller/ProductReviewController.java
=> [fix] 게이트웨이를 위한 상품, 결제 엔드포인트 수정

app-api/build.gradle, app-api/src/main/java/com/example/appapi/config/SwaggerConfig.java, resv-api/build.gradle, resv-api/src/main/java/com/example/resv/ResvApplication.java, resv-api/src/main/java/com/example/resv/config/SwaggerConfig.java, resv-api/src/main/resources/application.yml
=> [Feat] 예약 모듈 swagger 명세서 구현

app-api/src/main/java/com/example/appapi/handler/OAuth2SuccessHandler.java, app-api/src/main/java/com/example/appapi/users/KakaoService.java, app-api/src/main/java/com/example/appapi/users/UsersController.java
=> [Feature] 카카오로그인 front redirect (추후 front 경로수정 필요) #103

app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsRepository.java, app-api/src/main/java/com/example/appapi/orderProducts/model/OrderProducts.java, app-api/src/main/java/com/example/appapi/orderProducts/model/OrderProductsDto.java, app-api/src/main/java/com/example/appapi/product/review/controller/ProductReviewController.java, app-api/src/main/java/com/example/appapi/product/review/model/ProductReviews.java, app-api/src/main/java/com/example/appapi/product/review/model/ProductReviewsDto.java, app-api/src/main/java/com/example/appapi/product/review/repository/ProductReviewsRepository.java, app-api/src/main/java/com/example/appapi/product/review/service/ProductReviewsService.java
Mypage 상품 리뷰 기능(작성 가능한 리뷰 리스트)
=> [Feat] Mypage 상품 리뷰 기능

app-api/src/main/java/com/example/appapi/config/SwaggerConfig.java, app-api/src/main/java/com/example/appapi/store/model/StoreDto.java, resv-api/src/main/java/com/example/resv/config/ResvSwaggerConfig.java, resv-api/src/main/java/com/example/resv/resv/ResvController.java, resv-api/src/main/java/com/example/resv/resv/ResvRepository.java, resv-api/src/main/java/com/example/resv/resv/ResvService.java, resv-api/src/main/java/com/example/resv/resv/model/ResvDto.java
=> [Feat] 내 식당 예약 내역 조회 (SELLER) 구현, 예약 기능 수정

app-api/src/main/java/com/example/appapi/admin/AdminController.java, app-api/src/main/java/com/example/appapi/admin/AdminService.java, app-api/src/main/java/com/example/appapi/category/CategoryController.java, app-api/src/main/java/com/example/appapi/category/CategoryService.java, app-api/src/main/java/com/example/appapi/config/SecurityConfig.java, app-api/src/main/java/com/example/appapi/config/SwaggerConfig.java, app-api/src/main/java/com/example/appapi/product/service/ProductsService.java, app-api/src/main/java/com/example/appapi/store/StoreQueryRepository.java, app-api/src/main/java/com/example/appapi/store/StoreService.java, app-api/src/main/java/com/example/appapi/store/model/StoreDto.java, common/src/main/java/com/example/common/BaseResponseStatus.java, resv-api/build.gradle, resv-api/src/main/resources/application.yml
[Fix] 카테고리 생성 admin으로 이동
[Fix] 관리자 식당 조회 수정
[Fix] 메소드 이름 수정
[Fix] swagger config 수정
[Fix] yml 파일 수정
=> [Fix] 관리자 기능 수정, yml 파일 수정

app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsController.java, app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsService.java, app-api/src/main/java/com/example/appapi/orderProducts/model/OrderProductsDto.java, app-api/src/main/java/com/example/appapi/orders/OrdersController.java, app-api/src/main/java/com/example/appapi/orders/OrdersService.java, app-api/src/main/java/com/example/appapi/orders/model/OrdersDto.java
=> [Fix] 주문 부분 BaseResponse 추가(진행중)

app-api/src/main/java/com/example/appapi/delivery/DeliveryController.java, app-api/src/main/java/com/example/appapi/menus/MenusController.java, app-api/src/main/java/com/example/appapi/menus/model/MenusDto.java, app-api/src/main/java/com/example/appapi/orderProducts/OrderProductsController.java, app-api/src/main/java/com/example/appapi/orderProducts/model/OrderProductsDto.java, app-api/src/main/java/com/example/appapi/orders/OrdersController.java, app-api/src/main/java/com/example/appapi/orders/model/OrdersDto.java, app-api/src/main/java/com/example/appapi/store/model/StoreDto.java
주문 부분 BaseResponse 추가 및 Swagger 수정
=> [Fix] 주문 부분 BaseResponse 추가 및 Swagger 수정

app-api/src/main/java/com/example/appapi/delivery/DeliveryController.java, app-api/src/main/java/com/example/appapi/orders/OrdersRepository.java, app-api/src/main/java/com/example/appapi/store/StoreRepository.java
=> [Fix] 주문 부분 N+1 문제 수정

app-api/src/main/java/com/example/appapi/menus/MenusService.java, app-api/src/main/java/com/example/appapi/orders/OrdersService.java, app-api/src/main/java/com/example/appapi/orders/model/Orders.java, app-api/src/main/java/com/example/appapi/orders/model/OrdersDto.java, app-api/src/main/java/com/example/appapi/orders/orderProducts/OrderProductsController.java, app-api/src/main/java/com/example/appapi/orders/orderProducts/OrderProductsRepository.java, app-api/src/main/java/com/example/appapi/orders/orderProducts/OrderProductsService.java, app-api/src/main/java/com/example/appapi/orders/orderProducts/model/OrderProducts.java, app-api/src/main/java/com/example/appapi/orders/orderProducts/model/OrderProductsDto.java, app-api/src/main/java/com/example/appapi/product/controller/ProductsController.java, app-api/src/main/java/com/example/appapi/product/review/model/ProductReviews.java, app-api/src/main/java/com/example/appapi/product/review/model/ProductReviewsDto.java, app-api/src/main/java/com/example/appapi/product/review/service/ProductReviewsService.java, app-api/src/main/java/com/example/appapi/store/StoreRepository.java, app-api/src/main/java/com/example/appapi/store/model/StoreDto.java
=> [Fix] Orders 프로젝트 구조 수정
